# Generated by Django 3.1 on 2020-08-29 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('position', models.CharField(choices=[('GK', 'Portero'), ('DC', 'Central'), ('FBL', 'Lateral izquierdo'), ('FBR', 'Lateral derecho'), ('DC', 'Centrocampista'), ('MC', 'Medio centro'), ('AML', 'Media punta izquierda'), ('AMR', 'Media punta derecha'), ('AMC', 'Media punta centro'), ('ST', 'Delantero')], max_length=50, verbose_name='Posicion')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('opinion', models.CharField(blank=True, choices=[('A', 'G.O.A.T'), ('B', 'TOP'), ('C', 'Gostoso'), ('D', 'Not bad'), ('E', 'Pocho'), ('F', 'Muy pocho')], max_length=50, null=True, verbose_name='Opinion')),
            ],
        ),
    ]
