version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    volumes:
      - ./app:/app
      - static_volume:/celta_news/staticfiles
    command: >
      sh -c 'python3 manage.py wait_for_db &&
             gunicorn celta_news.wsgi:application --bind 0.0.0.0:8080'
    expose:
      - 8080
    env_file: .env.dev
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    env_file:
      - ./.env.dev
    ports:
      - "5433:5433"
    volumes: 
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:alpine
  celery:
    restart: always
    build:
      context: .
    command: celery -A celta_news beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - ./app:/app
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis
      - app
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/celta_news/staticfiles
    ports:
      - 1337:80
    depends_on:
      - app

volumes:
  pgdata:
  static_volume:
