# Generated by Django 3.1 on 2020-08-26 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager_first_name', models.CharField(max_length=50)),
                ('manager_last_name', models.CharField(max_length=50)),
                ('manager_email', models.EmailField(max_length=50)),
                ('manager_phone_number', models.CharField(max_length=20)),
                ('business_name', models.CharField(max_length=50)),
                ('business_email', models.EmailField(max_length=50)),
                ('business_country', models.CharField(max_length=50)),
                ('business_city', models.CharField(max_length=50)),
                ('business_address', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CommunityManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('phone_number', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
            ],
        ),
    ]
