# Generated by Django 4.0.2 on 2022-04-03 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_article_image_url_alter_article_url'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['title', '-created_at'], name='article_source_index'),
        ),
    ]
