version: '3'

services:
  app:
    image: arponpes/celta_novas:main
    container_name: app
    volumes:
      - ./app:/app
      - static_volume:/celta_novas/staticfiles
    command: >
      sh -c 'python3 manage.py wait_for_db &&
             gunicorn celta_novas.wsgi:application --bind 0.0.0.0:8080 &&
             celery -A celta_novas beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler &&
             celery -A celta_novas worker -l INFO --detach'
    expose:
      - 8080
    env_file: .env.prod
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    container_name: postgres
    env_file:
      - ./.env.prod
    ports:
      - "5433:5433"
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:latest
    container_name: redis
  nginx:
    build: ../nginx
    container_name: nginx
    volumes:
      - static_volume:/celta_novas/staticfiles
      - configs:/configs
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app

volumes:
  pgdata:
  static_volume:
  configs:
