name: Db dump

on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Creating DB backup
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        script: |
          python3 /celta-novas/celta-novas-infra/scripts/backup.py
          ls /backups
